# Generated by Django 4.2.3 on 2024-01-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_githuburl_project_livesite'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='introtext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=200),
        ),
    ]
